"""add creator_id to club

Revision ID: 8c08de56ab73
Revises: e03d1293cdf9
Create Date: 2026-07-01 16:14:42.962633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c08de56ab73'
down_revision: Union[str, Sequence[str], None] = 'e03d1293cdf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('club', sa.Column('creator_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'club', 'accounts', ['creator_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'club', type_='foreignkey')
    op.drop_column('club', 'creator_id')
    # ### end Alembic commands ###
