"""add club access control tables

Revision ID: e03d1293cdf9
Revises: e434e42e43a1
Create Date: 2026-06-28 11:32:40.555325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e03d1293cdf9'
down_revision: Union[str, Sequence[str], None] = 'e434e42e43a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('club_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['club_id'], ['club.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('club_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'rejected', name='status'), nullable=False),
    sa.Column('request_type', sa.Enum('request', 'invite', name='requesttype'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['club_id'], ['club.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.Enum('public', 'private', 'one_v_one', name='clubtype').create(op.get_bind())
    )
    op.add_column('club', sa.Column('club_type', sa.Enum('public', 'private', 'one_v_one', name='clubtype'), nullable=False,server_default='public'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('club', 'club_type')
    op.drop_table('club_requests')
    op.drop_table('club_members')
    # ### end Alembic commands ###
